//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edinica
    {
        public int ID_Edinica { get; set; }
        public string GUID_Donor { get; set; }
        public string Component { get; set; }
        public int FK_Status { get; set; }
        public System.DateTime Date_Sbora { get; set; }
        public Nullable<System.DateTime> Date_Freeze { get; set; }
        public string Group { get; set; }
        public string Rh { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
